---
- name: Install dnf packages
  become: true
  dnf:
    name:
      # essential build tools (gcc, make, etc)
      - "@development-tools"
      - libtool
      - python
      - python3
      - gtest-devel
      - gtest
      - gcc-c++
      - clang
      - jsoncpp-devel
      - xorg-x11-server-Xorg
      - xorg-x11-drv-evdev-devel
      - xorg-x11-drv-libinput-devel
      - xorg-x11-drv-openchrome-devel
      - xorg-x11-drv-synaptics-devel
      - xorg-x11-drv-wacom-devel
      - xorg-x11-proto-devel.noarch
      - xorg-x11-server-Xwayland-devel
      - xorg-x11-server-devel
      - xorg-x11-xtrans-devel

      # For bluetooth selinux fix
      - selinux-policy

      # Audio / CRAS dependencies
      - acpid
      - libudev-devel
      - sbc-devel
      - alsa-lib-devel
      - iniparser-devel
      - ladspa-devel
      - speex-devel
      - speexdsp-devel
    state: latest
