---
- hosts: all

  vars_prompt:
    - name: "eve_keyboard_search_keycode"
      prompt: "What keycode do you want the Search key to send? (see ansible/keycodes.txt)\n"
      default: "ctrl"
      private: no

    - name: "eve_keyboard_assistant_keycode"
      prompt: "What keycode do you want the Assistant key to send? (see ansible/keycodes.txt)\n"
      default: "leftmeta"
      private: no

  tasks:
  - name: Install pre-requisites
    include_role:
      name: common

  - name: Extract files from eve recovery image
    include_role:
      name: eve-recovery-files

  # - name: Install Chrome Audio Server and sound setup files
  #   include_role:
  #     name: eve-audio

  - name: Install ChromeOS X11 touchpad driver
    include_role:
      name: eve-touchpad

  - name: Install misc tweaks
    include_role:
      name: eve-tweaks
